spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka